export const GOVERNORATE_AREAS = {
  Damascus: [
    'Abu Rummaneh',
    'Al Maliki',
    'Al Mazzeh',
    'Al Muhajireen',
    'Al Qassaa',
    'Al Shaghour',
    'Al Tijara',
    'Bab Sharqi',
    'Bab Touma',
    'Barzeh',
    'Baramkeh',
    'Dummar',
    'Kafr Sousa',
    'Qanawat',
    'Rukn Al Din',
    'Sarouja',
    'Al Midan',
    'Yarmouk',
    'Jobar',
    'Al Hamra',
    'Al Asali',
    'Al Qaboun',
    'Tishreen',
    'Al Rawda',
    'Al Thawra',
    'Al Salihiyah',
    'Al Abbasiyyin',
    'Al Qaimariyah',
    'Al Amara',
    'Al Marja',
  ],
  'Rif Dimashq': [
    'Al Tall',
    'Jaramana',
    'Qudsaya',
    'Douma',
    'Harasta',
    'Saqba',
    'Zabadani',
    'Madaya',
    'Ain Minin',
    'Halbon',
    'Yabroud',
    'Nabk',
    'Qatana',
    'Darayya',
    'Moadamiyah',
    'Khan al-Shih',
    'Al Qutayfah',
    'Al Tayyibah',
    'Deir Atiyah',
    'Al Nabk',
    'Yalda',
    'Babbila',
    'Hajira',
    'Sahnaya',
    'Beit Jinn',
    'Qudsaya',
    'Al Hameh',
    'Artouz',
    'Jdeidet Artouz',
    'Al Kiswah',
    'Deir Qanun',
    'Al Ghizlaniyah',
    'Al Ma\'murah',
    'Al Qasimiyah',
    'Al Thiabiyah',
    'Al Ub',
    'Hawsh Arab',
    'Hawsh Dara',
    'Hawsh al-Harabir',
    'Kafr Hawar',
    'Qara',
    'Maaloula',
    'Sednaya',
    'Yabroud',
    'Rankous',
  ],
  Aleppo: [
    'New Aleppo',
    'Salah Al Din',
    'Al Furqan',
    'Al Aziziyah',
    'Al Jamiliyah',
    'Al Sulaymaniyah',
    'Al Sayyid Ali',
    'Al Midan',
    'Bab al-Nayrab',
    'Bab al-Faraj',
    'Bab al-Hadid',
    'Al Sha\'ar',
    'Al Furdaws',
    'Al Mashhad',
    'Al Bayyada',
    'Al Sabil',
    'Al Qalaji',
    'Al Ansari',
    'Al Zahra',
    'Al Zahraa',
    'Ramouseh',
    'Bustan al-Zahra',
    'Meydan',
    'Jebel Saman',
    'Ashrafiyah',
    'Sulaymaniyah',
    'Aziziyah',
    'Jamiliyah',
    'Saif al-Dawla',
    'Al Hamdaniyah',
    'Al Izaa',
    'Al Shahba',
    'Al Jalloum',
    'Bab Antakiyah',
    'Al Aqaba',
    'Al Baladiyah',
    'Al Kallaseh',
    'Al Masharqah',
    'Al Maghayir',
    'Al Marjeh',
    'Al Salihiyah',
    'Al Sukari',
    'Al Wurud',
    'Al Yarmouk',
    'Bab al-Nasr',
    'Karm al-Tarrab',
    'Karm al-Jabal',
    'Karm al-Loz',
    'Karm al-Hayek',
    'Karm al-Jazairi',
    'Karm al-Deir',
    'Karm al-Shami',
    'Karm al-Turkman',
    'Karm al-Khalidi',
    'Karm al-Maysar',
    'Karm al-Ansari',
    'Karm al-Rahman',
    'Karm al-Sadr',
    'Karm al-Zaytoun',
    'Karm al-Bustan',
    'Karm al-Nour',
    'Karm al-Huda',
    'Karm al-Salam',
    'Karm al-Amal',
    'Karm al-Nasr',
    'Karm al-Faraj',
    'Karm al-Shifa',
    'Karm al-Rahma',
    'Karm al-Baraka',
    'Karm al-Hayat',
    'Karm al-Saada',
    'Karm al-Jamal',
    'Karm al-Rawda',
    'Karm al-Nahda',
    'Karm al-Taj',
    'Karm al-Bahri',
    'Karm al-Qibli',
    'Karm al-Shamali',
    'Karm al-Gharbi',
    'Karm al-Sharqi',
  ],
  Homs: [
    'Al Waer',
    'Akrama',
    'Baba Amr',
    'Al Inshaat',
    'Al Ghouta',
    'Al Hamra',
    'Al Mahatta',
    'Al Sabeel',
    'Al Sinaa',
    'Al Thawra',
    'Al Zahra',
    'Al Zahraa',
    'Al Qusour',
    'Al Arbaeen',
    'Al Andalus',
    'Al Mreza',
    'Al Qusayr',
    'Al Rastan',
    'Al Qaryatayn',
    'Al Mukharram',
    'Al Dabaa',
    'Al Qadmous',
    'Al Mishirfeh',
    'Al Qattinah',
    'Al Karnaz',
    'Al Kafraya',
    'Al Houla',
    'Al Talbisah',
    'Deir Ful',
    'Hish',
    'Sadad',
    'Qarah',
    'Muhin',
    'Hosn',
    'Aqrab',
  ],
  Hama: [
    'Al Andalus',
    'Al Mreza',
    'Al Arbaeen',
    'Al Hamra',
    'Al Mahatta',
    'Al Sabeel',
    'Al Sinaa',
    'Al Thawra',
    'Al Zahra',
    'Al Zahraa',
    'Al Qusour',
    'Al Bayad',
    'Al Suq',
    'Al Jumhuriyah',
    'Al Shaikh',
    'Al Malaab',
    'Kafar Zita',
    'Karnaz',
    'Khirbet al-Naqus',
    'Lataminah',
    'Kafr Zita',
    'Morek',
    'Taybat al-Imam',
    'Souran',
    'Karnaz',
    'Al Lataminah',
    'Kafr Zita',
    'Morek',
    'Taybat al-Imam',
    'Souran',
  ],
  Lattakia: [
    'Al Ziraa',
    'Daatour',
    'Slaybeh',
    'Al Mina',
    'Al Ramel',
    'Old City',
    'Corniche',
    'Al Marqab',
    'Al Bahluliyah',
    'Al Qadmus',
    'Al Haffah',
    'Al Jableh',
    'Al Kadmous',
    'Al Qardaha',
    'Al Bahluliyah',
    'Al Marqab',
    'Al Mina',
    'Al Ramel',
    'Old City',
    'Corniche',
    'Al Ziraa',
    'Daatour',
    'Slaybeh',
    'Al Marqab',
    'Al Bahluliyah',
    'Al Qadmus',
    'Al Haffah',
    'Al Jableh',
    'Al Kadmous',
    'Al Qardaha',
  ],
  Tartous: [
    'Al Ramel',
    'Old City',
    'Corniche',
    'Al Bahr',
    'Al Arwad',
    'Al Sawda',
    'Al Hamidiyah',
    'Al Dreib',
    'Al Bahr',
    'Al Safita',
    'Al Mashta',
    'Al Qadmus',
    'Al Haffah',
    'Al Jableh',
    'Al Kadmous',
    'Al Qardaha',
    'Al Bahluliyah',
    'Al Marqab',
    'Al Mina',
    'Al Ramel',
    'Old City',
    'Corniche',
  ],
  Daraa: [
    'Al Mahatta',
    'Daraa Al Balad',
    'Sahil',
    'Al Muzayrib',
    'Al Jeezah',
    'Al Tafas',
    'Al Naima',
    'Al Bosra',
    'Al Sura',
    'Al Harrah',
    'Al Yadudah',
    'Al Kharab',
    'Al Tasil',
    'Al Saham',
    'Al Gariyah',
    'Al Nimer',
    'Al Dama',
    'Al Khazan',
    'Al Qusayr',
    'Al Kiswa',
    'Al Zayzoun',
    'Al Abasiyah',
    'Al Mazarib',
    'Al Daraa',
    'Al Jeezah',
    'Al Tafas',
    'Al Naima',
  ],
  'Deir ez-Zor': [
    'Al Joura',
    'Al Qusour',
    'Al Hamidiya',
    'Al Mayadin',
    'Al Bukamal',
    'Al Shuhail',
    'Al Susah',
    'Al Khasham',
    'Al Tabiyah',
    'Al Asharah',
    'Al Diban',
    'Al Kassra',
    'Al Marat',
    'Al Salihiyah',
    'Al Husaybah',
    'Al Jafra',
    'Al Quriyah',
    'Al Suwayr',
    'Al Mahkan',
    'Al Kharita',
    'Al Shaddadi',
    'Al Haskan',
    'Al Kabir',
    'Al Jisr',
    'Al Shuhail',
    'Al Susah',
    'Al Khasham',
    'Al Tabiyah',
    'Al Asharah',
    'Al Diban',
    'Al Kassra',
    'Al Marat',
  ],
  Hasakah: [
    'Al Nashwa',
    'Ghuwayran',
    'Salhiyah',
    'Al Qamishli',
    'Al Malikiyah',
    'Al Raqqah',
    'Al Shaddadi',
    'Al Yarubiyah',
    'Al Qahtaniyah',
    'Al Tell',
    'Al Hol',
    'Al Shadadi',
    'Al Haskan',
    'Al Kabir',
    'Al Jisr',
    'Al Shuhail',
    'Al Susah',
    'Al Khasham',
    'Al Tabiyah',
    'Al Asharah',
    'Al Diban',
    'Al Kassra',
    'Al Marat',
    'Al Salihiyah',
    'Al Husaybah',
    'Al Jafra',
    'Al Quriyah',
    'Al Suwayr',
    'Al Mahkan',
    'Al Kharita',
  ],
  Raqqa: [
    'Al Matar',
    'Al Daraiya',
    'Mansour',
    'Al Raqqa',
    'Al Tabqa',
    'Al Thawra',
    'Al Sabkha',
    'Al Karama',
    'Al Maskan',
    'Al Jurniyah',
    'Al Hamra',
    'Al Qadsiyah',
    'Al Rashid',
    'Al Saqr',
    'Al Salihiyah',
    'Al Husaybah',
    'Al Jafra',
    'Al Quriyah',
    'Al Suwayr',
    'Al Mahkan',
    'Al Kharita',
    'Al Shaddadi',
    'Al Haskan',
    'Al Kabir',
    'Al Jisr',
    'Al Shuhail',
    'Al Susah',
    'Al Khasham',
    'Al Tabiyah',
    'Al Asharah',
    'Al Diban',
    'Al Kassra',
    'Al Marat',
  ],
  Suwayda: [
    'Al Qanawat',
    'Salkhad',
    'Shahba',
    'Al Suwayda',
    'Al Jumla',
    'Al Thawra',
    'Al Masaa',
    'Al Quds',
    'Al Safa',
    'Al Kharab',
    'Al Nimer',
    'Al Dama',
    'Al Khazan',
    'Al Qusayr',
    'Al Kiswa',
    'Al Zayzoun',
    'Al Abasiyah',
    'Al Mazarib',
    'Al Daraa',
    'Al Jeezah',
    'Al Tafas',
    'Al Naima',
    'Al Bosra',
    'Al Sura',
    'Al Harrah',
    'Al Yadudah',
    'Al Kharab',
    'Al Tasil',
    'Al Saham',
    'Al Gariyah',
  ],
  Quneitra: [
    'Khan Arnabeh',
    'Al Baath',
    'Hader',
    'Al Quneitra',
    'Al Jumla',
    'Al Thawra',
    'Al Masaa',
    'Al Quds',
    'Al Safa',
    'Al Kharab',
    'Al Nimer',
    'Al Dama',
    'Al Khazan',
    'Al Qusayr',
    'Al Kiswa',
    'Al Zayzoun',
    'Al Abasiyah',
    'Al Mazarib',
    'Al Daraa',
    'Al Jeezah',
    'Al Tafas',
    'Al Naima',
    'Al Bosra',
    'Al Sura',
    'Al Harrah',
    'Al Yadudah',
    'Al Kharab',
    'Al Tasil',
    'Al Saham',
    'Al Gariyah',
  ],
}

export const GOVERNORATES = Object.keys(GOVERNORATE_AREAS)

